name: Prey on frontend code
on:
  push:
    branches:
      - main
    paths:
      - frontend/**
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: 
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}
        with:
          projectBaseDir: frontend
          args: >
            -Dsonar.organization=adrianrudnik
            -Dsonar.projectKey=ablegram.frontend
